version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  vector_service:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: uvicorn app.vector_service:app --port 5000 --host 0.0.0.0
  api_server:
    build: .
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - mongodb
      - celery
      - vector_service
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0
  celery:
    build: .
    container_name: celery_worker
    command: [ "celery", "-A", "app.celery:celery_app", "worker", "--loglevel=info" ]
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app
    env_file:
      - .env
  redis:
    image: "redis:6.0-alpine"
    container_name: redis
    ports:
      - "6379:6379"
 
volumes:
  mongo-data: