version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  api_server:
    build: .
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --port 8000 --host 0.0.0.0
 
volumes:
  mongo-data: